version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mynetwork
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  yourapp:
    build:
      context: ./your-app-directory
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql
      - redis
      - elasticsearch
    networks:
      - mynetwork
    environment:
      - ConnectionStrings__MssqlConnection=Server=mssql;Database=YourDatabase;User Id=sa;Password=YourPassword123!
      - Redis__Configuration=redis:6379
      - Elasticsearch__Url=http://elasticsearch:9200

networks:
  mynetwork:
